spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8080

app:
  jwt:
    secret: your-jwt-secret-key-here
    expiration: 86400000

logging:
  level:
    com.taskflow: DEBUG
